import type { Metadata } from "next";

import "./globals.css";
import { connectToDbIfNotConnected } from "@/middleware/connectToDbIfNotConnected";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Next BDD server",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDbIfNotConnected();
  return (
    <html lang="en">
      <body className={` antialiased`}>
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
